using OLTMockServer.DataStructures;
using OLTMockServer.spag;
using spag;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OLTMockServer.MockServers
{
    public abstract class MockServer
    {
        protected readonly WCFServiceManager serviceManager;
        protected readonly OrderFactory orderFactory;

        protected MockServer(OrderFactory orderFactory)
        {
            this.serviceManager = new WCFServiceManager();
            this.orderFactory = orderFactory;

            var services = GetServices;

            if (services != null)
            {
                foreach (var serviceInfo in services)
                {
                    //log...
                    this.serviceManager.RegisterService(
                        serviceInfo.ServiceName,
                        serviceInfo.BaseUrl,
                        serviceInfo.ServiceClassInstance,
                        serviceInfo.ServiceInterfaceType);
                }
            }
        }

        public bool IsServerStarted
        {
            get { return this.serviceManager.IsAnyServiceStarted(); }
        }

        public bool StartServer()
        {
            try
            {
                if (IsServerStarted)
                {
                    throw new InvalidOperationException("Cannot start server, Server already started");
                }

                this.serviceManager.StartAll();

                return true;
            }
            catch (Exception ex)
            {
                //log
                return false;
            }
        }

        public bool StopServer()
        {
            try
            {
                if (!IsServerStarted)
                {
                    throw new InvalidOperationException("Cannot stop server, Server is not started.");
                }

                this.serviceManager.StopAll();

                return true;
            }
            catch (Exception ex)
            {
                //log
                return false;
            }
        }

        public bool SendOrder(Order order, Vendor targetVendor)
        {
            var methodNameInVendor = GetAPIMethodName(Definitions.APINames.NewOrder);

            var objectToSend = GetSendModel(order);

            if (APIUtil.CallApi(methodNameInVendor, objectToSend, RestSharp.Method.POST, targetVendor.BaseUrl))
            {
                return true;
            }

            //log
            return false;
        }

        protected abstract object GetSendModel(Order order);

        public Order CreateNewOrder(OrderPattern pattern, bool isAutoGenerated)
        {
            var newOrder = orderFactory.CreateNewOrder(pattern, isAutoGenerated);
            AddDefaultActivitiesToNewOrder(newOrder);
            newOrder.AddLog($"Order Created {(isAutoGenerated ? "by auto":"by user")}");
            return newOrder;
        }

        protected abstract void AddDefaultActivitiesToNewOrder(Order newOrder);

        public string GetDefaultTestTitle
        {
            get
            {
                return $"Test-{OnlineShopType}";
            }
        }

        public abstract List<MockServerServiceInfo> GetServices { get; }
        public abstract string GetAPIMethodName(Definitions.APINames apiName);

        public bool PerformOrderActivity(Order order, Vendor vendor, OrderActivity activity)
        {
            try
            {
                activity.LastTryDate = DateTime.Now;

                switch (activity.ActivityType)
                {
                    case Definitions.OrderActivityTypes.Send:
                    case Definitions.OrderActivityTypes.Edit:
                    case Definitions.OrderActivityTypes.Reject:

                        order.StatusCode = GetActivityStatusCode(activity.ActivityType);
                        return SendOrder(order, vendor);

                    case Definitions.OrderActivityTypes.None:
                    default:
                        return false;
                }
            }
            catch (Exception ex)
            {
                activity.LastTryExceptionMessage = ex.Message;

                return false;
            }
        }

        protected abstract string GetActivityStatusCode(Definitions.OrderActivityTypes activityType);

        public abstract Definitions.KnownOnlineShops OnlineShopType { get; }
    }
}
