using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Drawing.Design;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;
using Telerik.WinControls.UI;
using static OLTMockServer.Definitions;

namespace OLTMockServer.DataStructures
{
    [XmlInclude(typeof(Snap.SnapOrder))]
    [Serializable]
    public abstract class Order
    {
        public Order()
        {
            this.Items = new List<Item>();
            this.Customer = new Customer();
            this.Vendor = new Vendor();
            this.CreateDate = DateTime.Now;
            this.Code = Utils.GenerateCode(8);
            this.Activities = new List<OrderActivity>();
            this.UId = Guid.NewGuid();
            this.Logs = new List<LogInfo>();
            this.MaxItemCount = 1;
        }

        [Browsable(false)]
        public Guid UId { get; set; }

        [Browsable(false)]
        public List<Item> Items { get; set; }

        public string Code { get; set; }

        [Browsable(false)]
        public Customer Customer { get; set; }

        [Browsable(false)]
        public Vendor Vendor { get; set; }

        [NotEditable]
        public bool Rejected { get; set; }

        [NotEditable]
        public bool RejectedByVendor { get; set; }

        public DateTime CreateDate { get; set; }

        public string StatusCode { get; set; }
        public string StatusDescription { get; set; }

        [Browsable(false)]
        public DateTime AcceptTime { get; set; }

        [Browsable(false)]
        public DateTime PickTime { get; set; }

        [Browsable(false)]
        public DateTime AckTime { get; set; }

        [Browsable(false)]
        public DateTime RejectTime { get; set; }

        public string DeliveryMode { get; set; }

        [Browsable(false)]
        public bool IsAutoGenerated { get; set; }

        [Browsable(false)]
        public List<LogInfo> Logs { get; set; }

        public int MaxItemCount { get; set; }

        [XmlIgnore]
        [Browsable(false)]
        public bool IsSelected { get; set; }

        /// <summary>
        /// Find last successfull send activty if exists.
        /// </summary>
        [Browsable(false)]
        public OrderActivity SendSuccessActivity
        {
            get
            {
                return Activities.FindLast(a => a.ActivityType == OrderActivityTypes.Send && a.IsDone == true);
            }
        }

        /// <summary>
        /// Find last send activty if exists (whether sent or not).
        /// </summary>
        [Browsable(false)]
        public OrderActivity SendActivity
        {
            get
            {
                return Activities.FindLast(a => a.ActivityType == OrderActivityTypes.Send);
            }
        }

        /// <summary>
        /// Find last successfull sent edit activty if exists.
        /// </summary>
        [Browsable(false)]
        public OrderActivity EditSuccessActivity
        {
            get
            {
                return Activities.FindLast(a => a.ActivityType == OrderActivityTypes.Edit && a.IsDone == true);
            }
        }

        /// <summary>
        /// Find last edit activty if exists (whether sent or not).
        /// </summary>
        [Browsable(false)]
        public OrderActivity EditActivity
        {
            get
            {
                return Activities.FindLast(a => a.ActivityType == OrderActivityTypes.Edit);
            }
        }

        /// <summary>
        /// Find any successfully sent activity (Edit or Send)
        /// </summary>
        [Browsable(false)]
        public OrderActivity AnySuccessSendActivity
        {
            get
            {
                if (SendSuccessActivity != null)
                {
                    return SendSuccessActivity;
                }
                else if (EditSuccessActivity != null)
                {
                    return EditSuccessActivity;
                }
                else
                {
                    return null;
                }
            }
        }

        [Browsable(false)]
        public DateTime BaseTime
        {
            get
            {
                if (AnySuccessSendActivity != null)
                {
                    return AnySuccessSendActivity.ProcessDate;
                }
                else
                {
                    return CreateDate;
                }
            }
        }

        [Browsable(false)]
        public bool IsSent
        {
            get
            {

                return SendSuccessActivity != null || EditSuccessActivity != null;
            }
        }

        //[Browsable(false)]
        public TimeSpan AckDelay
        {
            get
            {
                if (AckTime != DateTime.MinValue)
                {
                    return TimeSpan.FromSeconds((long)(AckTime - BaseTime).TotalSeconds);
                }

                return TimeSpan.Zero;
            }
        }

        //[Browsable(false)]
        public TimeSpan PickDelay
        {
            get
            {
                if (PickTime != DateTime.MinValue)
                {
                    return TimeSpan.FromSeconds((long)(PickTime - BaseTime).TotalSeconds);
                }

                return TimeSpan.Zero;
            }
        }

        //[Browsable(false)]
        public TimeSpan AcceptDelay
        {
            get
            {
                if (AcceptTime != DateTime.MinValue)
                {
                    return TimeSpan.FromSeconds((long)(AcceptTime - BaseTime).TotalSeconds);
                }

                return TimeSpan.Zero;
            }
        }

        //[Browsable(false)]
        public OrderStatusResults UIStatus
        {
            get
            {
                var sendActivity = SendActivity;
                var editActivity = EditActivity;
                bool isAckReceived = AckTime != DateTime.MinValue;
                bool isPickReveived = PickTime != DateTime.MinValue;
                bool isAccepted = AcceptTime != DateTime.MinValue;

                bool isEdited = editActivity?.IsDone ?? false;

                OrderStatusResults status = OrderStatusResults.Unknown;

                if (IsSent)
                {
                    status = OrderStatusResults.Sent;

                    if (isAckReceived)
                    {
                        status = OrderStatusResults.AckDone;
                    }

                    if (isPickReveived)
                    {
                        status = OrderStatusResults.PickDone;
                    }

                    if (isAccepted)
                    {
                        status = OrderStatusResults.Accepted;
                    }

                    if (Rejected)
                    {
                        status = OrderStatusResults.RejectedByServer;
                    }

                    if (RejectedByVendor)
                    {
                        status = OrderStatusResults.RejectedByVendor;
                    }
                }
                else
                {
                    if ((sendActivity != null && sendActivity.TryCount > 0) || (EditActivity != null && editActivity.TryCount > 0))
                    {
                        status = OrderStatusResults.SendFailed;
                    }
                    else
                    {
                        status = OrderStatusResults.NotSend;
                    }
                }

                return status;
            }
        }

        [Browsable(false)]
        public List<OrderActivity> Activities { get; set; }

        public void AddActivity(Definitions.OrderActivityTypes activityType, bool isAutoActivity)
        {
            this.Activities.Add(new OrderActivity
            {
                //OrderInstance = LightClone(),
                ActivityDate = DateTime.Now,
                ActivityType = activityType,
                IsCreatedByAuto = isAutoActivity,
            });
        }

        public abstract Order LightClone(bool keepId = false);

        [Browsable(false)]
        public bool HasNotPrcessedActivity
        {
            get
            {
                return this.Activities.Any(a => a.ProcessDate == DateTime.MinValue && a.TryCount < Definitions.Order_Max_Activity_Try_Count);
            }
        }

        public void AddLog(string title, string message, Definitions.LogTypes logType = LogTypes.None, params object[] args)
        {
            if (args != null && args.Length > 0)
            {
                message = string.Format(message, args);
            }

            if (!string.IsNullOrEmpty(message) && !string.IsNullOrEmpty(title))
            {
                Logs.Add(new LogInfo(title, message, logType));
            }
            else if (!string.IsNullOrEmpty(message))
            {
                Logs.Add(new LogInfo(message, logType));
            }
            else
            {
                Logs.Add(new LogInfo());
            }
        }

        public void AddLog(string message, Definitions.LogTypes logType = LogTypes.None, params object[] args)
        {
            if (args != null && args.Length > 0)
            {
                message = string.Format(message, args);
            }

            if (!string.IsNullOrEmpty(message))
            {
                Logs.Add(new LogInfo(message, logType));
            }
            else
            {
                Logs.Add(new LogInfo());
            }
        }
    }
}
